services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: webhook_user
      POSTGRES_PASSWORD: webhook_password
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webhook_user -d webhook_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  webhook:
    build: .
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://webhook_user:webhook_password@postgres:5432/webhook_db
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run db:migrate && node .next/standalone/server.js"

volumes:
  postgres_data:
