# fly.toml app configuration file
app = 'cosmetics-data-hub-v2'
primary_region = 'sea'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[deploy]
  release_command = 'npm run db:migrate'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/webhook'

[[vm]]
  size = 'shared-cpu-1x'
